version: "3.5"
services:
  api:
    image: node:12
    container_name: commando_api
    volumes:
      - .:/Documents/devstack/Test/docker-nodejs-api
    working_dir: /usr/src/app
    command: npm start
    links:
      - db
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "123456"
    ports:
      - "3307:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
